# Generated by Django 3.0.7 on 2020-08-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='change_dark_color',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='change_light_color',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='keys_for_mevement',
        ),
    ]
