# Generated by Django 3.1.3 on 2020-12-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_color_value', models.CharField(blank=True, default='Black', max_length=500, null=True)),
                ('light_color_value', models.CharField(blank=True, default='White', max_length=500, null=True)),
                ('voice_assistant', models.BooleanField(default=True)),
                ('use_numpad_keys_for_movement', models.BooleanField(default=True, verbose_name='use numpad keys for movement of pieces')),
            ],
            options={
                'db_table': 'Settings',
            },
        ),
    ]
