# Generated by Django 3.1.3 on 2020-12-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20201228_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='user',
        ),
    ]
