# Generated by Django 3.1.3 on 2020-12-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_data_path', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('relative_path', models.BooleanField(blank=True, default=False, null=True)),
                ('game_data_content', models.JSONField(default={})),
            ],
        ),
    ]
