# Generated by Django 3.1.3 on 2020-12-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_data_content',
            field=models.JSONField(default=dict),
        ),
    ]
