# Generated by Django 3.1.3 on 2021-01-04 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('tournaments', '0001_initial'),
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='game.game'),
        ),
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='tournaments.room'),
        ),
    ]
