# Generated by Django 3.1.3 on 2020-11-29 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20201127_0039'),
        ('UserAuth', '0003_auto_20200822_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='tournaments.room'),
        ),
    ]
